apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nubenetes-root-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/nubenetes/jenkins-git-parameter.git'
    targetRevision: main
    path: argocd-apps/apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
